@startuml
'https://plantuml.com/object-diagram

object GameSession{
}
object PlayerHandler{
}
object Server{
}
object PlayerPool{
}
object PlayerSocket{
}
object RankSystem{
}
object Client

Client - Server: communicate
Server -> PlayerHandler: create
Server -> PlayerSocket: create
@enduml
